---
version: 2.1

setup: true

# ----------------
# Orbs declaration
# ----------------

orbs:

  orb-tools: circleci/orb-tools@12.0.4



# -----------------
# Pipeline workflow
# -----------------

# https://github.com/CircleCI-Public/Orb-Template/blob/main/.circleci/config.yml
# https://circleci.com/docs/testing-orbs/

workflows:

  # This workflow will run on every commit
  lint-build:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - approve-for-testing:
          type: approval
          requires:
            - orb-tools/pack
            - orb-tools/lint
      # Release dev version of orb, for testing & possible publishing.
      - orb-tools/publish:
          vcs_type: github
          orb_name: noosenergy/noos-ci
          context: CIRCLECI_ORB_SHARED
          requires:
            - approve-for-testing
      - orb-tools/continue:
          vcs_type: github
          orb_name: noosenergy/noos-ci
          context: CIRCLECI_ORB_SHARED
          pipeline_number: << pipeline.number >>
          requires:
            - orb-tools/publish
