---
version: 2.1

setup: true

# ----------------
# Orbs declaration
# ----------------

orbs:
  orb-tools: circleci/orb-tools@12.0.4

# -----------------
# Pipeline workflow
# -----------------

# https://github.com/CircleCI-Public/Orb-Template/blob/main/.circleci/config.yml
# https://circleci.com/docs/testing-orbs/

workflows:

  # This workflow will run on every commit
  lint_build:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/review:
          exclude: "RC005,RC009"
      - approve_for_testing:
          type: approval
          requires:
            - orb-tools/pack
            - orb-tools/lint
            - orb-tools/review
      # Release dev version of orb, for testing & possible publishing.
      - orb-tools/publish:
          vcs_type: << pipeline.project.type >>
          orb_name: noosenergy/noos-ci
          context: CIRCLECI_ORB_SHARED
          requires:
            - approve_for_testing
      - orb-tools/continue:
          vcs_type: << pipeline.project.type >>
          orb_name: noosenergy/noos-ci
          context: CIRCLECI_ORB_SHARED
          pipeline_number: << pipeline.number >>
          requires:
            - orb-tools/publish
