---

description: Configure Docker remote registry [AWS ECR or Dockerhub].

parameters:
  registry-provider:
    type: enum
    enum: ["aws", "docker"]
    default: "aws"
    description: Docker registry provider.

steps:
  - when:
      condition:
        equal: [aws, << parameters.registry-provider >>]
      steps:
        - aws-cli/install
        - run:
            name: Configure AWS ECR registry
            command: noosinv docker.login
            environment:
              NOOSINV_DOCKER_REPO: $AWS_ECR_URL
  - when:
      condition:
        equal: [docker, << parameters.registry-provider >>]
      steps:
        - run:
            name: Configure Dockerhub registry
            command: noosinv docker.login
            environment:
              NOOSINV_DOCKER_USER: $DOCKERHUB_USER
              NOOSINV_DOCKER_TOKEN: $DOCKERHUB_TOKEN
