description: Configure Helm remote registry [Chart Museum].

steps:
  - run:
      name: Provision Helm client
      command: noosinv helm.install
  - run:
      name: Configure Helm registry
      command: noosinv helm.login
      environment:
        NOOSINV_HELM_URL: $CHARTMUSEUM_URL
        NOOSINV_HELM_USER: $CHARTMUSEUM_USER
        NOOSINV_HELM_TOKEN: $CHARTMUSEUM_TOKEN
