---
description: Spinup Python virtual environment using uv.

parameters:
  install_args:
    type: string
    default: "--dev"
    description: Arguments to pass to the install command.
  configure_git:
    type: boolean
    default: false
    description: Whether to setup git credentials.

steps:
  - when:
      condition: << parameters.configure_git >>
      steps:
        - run:
            name: Configure Github access
            command: noosinv git.config
            environment:
              NOOSINV_GIT_TOKEN: $GITHUB_TOKEN
  - restore_cache:
      keys:
        - "virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-\
          {{ checksum \"uv.lock\" }}"
        - virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
        - virtualenv-{{ .Environment.CACHE_VERSION }}-
  - run:
      name: Install Python packages
      command: |
        uv lock --check
        uv sync --frozen << parameters.install_args >>
  - save_cache:
      key: "virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-\
        {{ checksum \"uv.lock\" }}"
      paths:
        - "./.uv-cache"
