# https://hub.docker.com/r/cimg/python
# https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/python/images

description: Preconfigured CircleCI Python image.

docker:
  - image: noosenergy/circleci:latest

working_directory: "~/project"
