---

# https://hub.docker.com/r/noosenergy/circleci
# https://github.com/noosenergy/noos-docker-images/tree/master/docker/circleci

description: Preconfigured CircleCI Python image.

parameters:
  tag:
    type: string
    default: latest

docker:
  - image: noosenergy/circleci:<< parameters.tag >>

working_directory: "~/project"
