name: PR Agent Template

on:
  workflow_call:

jobs:
  pr_agent_job:
    if: github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          pr_reviewer.enable_review_labels_security: false
          pr_reviewer.enable_review_labels_effort: false
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
